Ucat faculties and administration coordination
hamalsolutions/ucat-enrrollment-dashboard pull request #7
Opened 2021-08-26 22:20 UTC by fabiolayerim

2021-08-31 13:09 UTC, maacaro approved these changes
LGTM

2021-09-01 09:49 UTC, hamalsolutions requested changes
@fabiolayerim creo que se pueden unir facultiescon admissiones y crear un solo componente Applicants o ApplicantsList 
en cada una de estas listas se debe poder observar los documentos y poder aprobar o no la diferncia es que son distintos ususarios

2021-09-01 09:49 UTC, hamalsolutions commented on cypress/integration/admission-coordination.spec.js
> +    cy.visit("/admission-coordination");
@fabiolayerim is there a link to click nad go to this page, or should be redirect after login?

2021-09-01 09:49 UTC, hamalsolutions commented on src/pages/admissionCoordination/admission.js
> +                  <th>Adjuntar Planilla</th>
@fabiolayerim why in the dashboard we need to "adjuntar planilla"

2021-09-01 09:49 UTC, hamalsolutions commented on src/pages/admissionCoordination/admission.js
> +import React from "react";
@fabiolayerim this page is a list of `applicants` I would call this `pages/applicants/applicants`

2021-09-01 09:49 UTC, hamalsolutions commented on src/pages/admissionCoordination/admissionContainer.js
> +import React from "react";
@fabiolayerim I would call this `pages/applicants/applicantsContainer`
we migth use this later to build the other views of this list you now in admmisiones, socie-economico and so on and so forth

2021-09-01 09:49 UTC, hamalsolutions commented on src/pages/admissionCoordination/admission.js
> +                  <th>Adjuntar Planilla</th>
@fabiolayerim shouldn't we just have la planilla and siplayed in a modal?

2021-09-01 09:49 UTC, hamalsolutions commented on src/pages/faculties/faculties.js
> +import React from "react";
@fabiolayerim can we just use the applicants componets with diferents props to create this view?

2021-09-01 09:49 UTC, hamalsolutions commented on src/pages/admissionCoordination/admission.js
> +
@fabiolayerim why we dont have here CTA to aprove or not approve the check like there are in faculties

2021-09-02 09:08 UTC, fabiolayerim commented on cypress/integration/admission-coordination.spec.js
> +    cy.visit("/admission-coordination");
currently the view is just jsx and has no redirect validation or a link

2021-09-02 10:03 UTC, maacaro requested changes
@fabiolayerim lo que creo es que esas 2 vistas con un solo componente que va cargar datos dependiendo del ususuario lo podemos discutir en el meeting

2021-09-02 10:03 UTC, maacaro commented on src/App.js
>              <Admission />
@fabiolayerim shouldn't be applicants too?

2021-09-08 17:14 UTC, maacaro approved these changes
LGTM

2021-09-08 17:52 UTC, hamalsolutions approved these changes
LGTM

2021-09-08 17:55 UTC, merged